### ISSUE TITLE
NameError: name 't' is not defined in pyfmi.simulation.assimulo_interface.FMIODE2.handle_event()

### ISSUE THREAD

**Issue by OscarPellicer** [modelon-community/PyFMI#100]
Hi,

I have using this Library over the last few weeks, and I am running into a randomly-occuring issue which I have not yet been able to track down. The traceback is the following:

```{python}
NameError                                 Traceback (most recent call last)
<ipython-input-6-923a097e3602> in <module>
     92 
     93 #Simulate
---> 94 res = model.simulate(final_time=N_days, options=opts, input=input)
     95 
     96 

src\pyfmi\fmi.pyx in pyfmi.fmi.FMUModelME2.simulate()

src\pyfmi\fmi.pyx in pyfmi.fmi.ModelBase._exec_simulate_algorithm()

src\pyfmi\fmi.pyx in pyfmi.fmi.ModelBase._exec_simulate_algorithm()

~\miniconda3\envs\modelica2\lib\site-packages\pyfmi\fmi_algorithm_drivers.py in solve(self)
    551 
    552         try:
--> 553             self.simulator.simulate(self.final_time, self.ncp)
    554         except:
    555             self.result_handler.simulation_end() #Close the potentially open result files

assimulo\ode.pyx in assimulo.ode.ODE.simulate()

assimulo\ode.pyx in assimulo.ode.ODE.simulate()

assimulo\explicit_ode.pyx in assimulo.explicit_ode.Explicit_ODE._simulate()

assimulo\explicit_ode.pyx in assimulo.explicit_ode.Explicit_ODE._simulate()

src\pyfmi\simulation\assimulo_interface.pyx in pyfmi.simulation.assimulo_interface.FMIODE2.handle_event()

NameError: name 't' is not defined
```

The issue might happen at some random time during the simulation, and after resetting the Python kernel (I am working from a Jupyter Notebook) it may or may not happen again (it happens around 10-20% of the time). It must be noted that the values of the inputs can be different in each run, but the input times are exactly the same.

I have tried to find the issue by myself, but since part of the code is in cython, the problem is not trivial to debug (for me at least). Also, it might be an Assimulo problem, but I cannot tell for sure.

The relevant code is the following:
```{python}
model = load_fmu('%s.fmu'%model_name)
opts = model.simulate_options() 
opts['result_handling']= 'memory'
opts['solver']= 'Dopri5'
opts['Dopri5_options']=\
        {'atol': 1e-05,
         'rtol': 0.001,
         'inith': 0.001, 
        'verbosity': 50} 
opts['ncp'] = 200
res= model.simulate(final_time=30, options=opts, input=input)
```
By the way, I am using Dormand-Prince instead of CVode because CVode fills up my RAM extremely quickly during longer simulations, but that is another question...

I am running windows 10 and I installed PyFMI using Anaconda: `conda install -c conda-forge pyfmi`

As of now, I am unfortunately unable to upload the FMU that I am using, but any guidance in solving the issue would be appreciated!

Thank you for your help!

**Comment by chria** [comment]
Hi!
Thanks for the report. The relevant lines are: https://github.com/modelon-community/PyFMI/blob/master/src/pyfmi/simulation/assimulo_interface.pyx#L900 . In the exception that we throw on this line we refer to the variable "t" where we should instead refer to "solver.t". However, even when this is fixed you'll still get the exception and the exception is due to that the evaluation of the derivatives in the FMU fails at this point. So you'll need to look into why the evaluation of the FMU would fail at this point.

**Comment by chria** [comment]
We'll fix so that the proper exception is displayed in the next release.

**Comment by OscarPellicer** [comment]
Ok, that makes a lot of sense. And a proper error message would be much appreciated.
