### ISSUE TITLE
[DOC] Install error using conda the way docs explain

### ISSUE THREAD

**Issue by canbooo** [modelon-community/PyFMI#111]
The [documentation](https://jmodelica.org/pyfmi/installation.html#requirements) suggests using
`conda install -c https://conda.binstar.org/chria pyfmi`
for the installation but this causes the following Error on Windows 10 and conda 4.10.1
```
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: chria
  channel url: https://conda.binstar.org/chria
  error code: 404
```

Using the `conda-forge` channels seems to do the trick, 

`conda install -c conda-forge pyfmi`

as suggested for [another issue](https://github.com/modelon-community/PyFMI/issues/42#issuecomment-678119607)

Please update the docs.

**Comment by modelonrobinandersson** [comment]
Hi @canbooo I have opened a PR to resolve this, thank you.
