### ISSUE TITLE
Issue in defining "step_size" for simulation

### ISSUE THREAD

**Issue by manasdas17** [modelon-community/PyFMI#112]
I'm trying to specify the "**step size**" in a single fmu simulation by the this way

```
sub_system1 = load_fmu("name.fmu")
opts= sub_system1.simulate_options()
opts["step_size"] = 0.01
```
But while executing i'm getting the error as

```
File "test.py", line 38, in <module>
    opts["step_size"] = 0.01
  File "C:\Users\OMM\Anaconda3\lib\site-packages\pyfmi\common\algorithm_drivers.py", line 306, in __setitem__
    "The key: %s, is not a valid option" %str(key))
pyfmi.common.algorithm_drivers.UnrecognizedOptionError: The key: step_size, is not a valid option
```
Is this the correct way of defining the **step_size** or there is any other method of defining it?

Regards,

**Comment by chria** [comment]
Specifying the step size is a solver specific option. I.e. you need to set it for the specific solver you are using. Are you after setting the step size for a specific fixed step solver that you have chosen for your simulation or are you interested in getting the result at a specific interval?

**Comment by manasdas17** [comment]
I want to know if it's possible to set step size for a fixed step solver in PyFMI. I'm using CVode co-simulation type FMU.

**Comment by chria** [comment]
If you are using CVode, then you are not using a fixed step solver, i.e. a (fixed) step-size is not applicable to these solvers. However, I guess what you are after is really getting the result at certain intervals. If you are using a Co-Sim FMU, just set the "ncp" (number of communication intervals) to the number of points you want and you'll get the result back at intervals = (stop_time - start_time)/ncp

**Comment by kiriatgit** [comment]
> If you are using CVode, then you are not using a fixed step solver, i.e. a (fixed) step-size is not applicable to these solvers. However, I guess what you are after is really getting the result at certain intervals. If you are using a Co-Sim FMU, just set the "ncp" (number of communication intervals) to the number of points you want and you'll get the result back at intervals = (stop_time - start_time)/ncp

I tried this method with ncp to set result at certain intervals. But it doesn't work in my case. Is there any other ways? Thanks

res = heatpump.simulate(start_time=0, final_time=360000, input=input_hp, options={'ncp':100})
len(res['time']) = 2401
