### ISSUE TITLE
Co-smulation of 2 FMUs fails for one fmu at a particular time step

### ISSUE THREAD

**Issue by manasdas17** [modelon-community/PyFMI#115]
Hello,
I am using PyFMI to simulate a coupled simulation of two FMUs 
(Control.fmu and Plant.fmu) as shown below.

```import matplotlib.pyplot as plt
from pyfmi import load_fmu

fmu_control = load_fmu('Control.fmu'); fmu_plant = load_fmu('Plant.fmu')

List models
models = [fmu_control, fmu_plant]
Set up connections between models
connections = [(fmu_control, 'y1', fmu_plant, 'u1'), (fmu_control, 'y2', fmu_plant, 'u2')]

Create coupled co-simulation object
from pyfmi.master import Master
coupled_simulation = Master(models, connections)

opts = coupled_simulation.simulate_options()
opts['step_size'] = 1

res = coupled_simulation.simulate(final_time = 18000.0, options=opts)
```

The simulation seems to fail at some time point and getting the below error
**pyfmi.fmi.FMUException: The step failed for model fmu_control at time 9239.000000. 
See the log for more information. Return flag 2**

Please let me know why this issue is occurring.

**Comment by chria** [comment]
The problem is in the setup / or the FMUs. It could be an instability in the setup which causes the FMU to fail to take a step forward.
