### ISSUE TITLE
Issue on the reset function provided by the PyFMI package

### ISSUE THREAD

**Issue by xifanghnu** [modelon-community/PyFMI#116]
I try to implement the reinforcement learning based HVAC system control by the Energyplus-Python co-simulation with FMI standard.  I want to reset and initilalize the FMU model after every epoch when the reinforcement learning control is implemented. I used the reset function provided by Pyfmi package, but it failed. 

   The code is as follows. I want to reset and initilalize the FMU model after every epoch (i_episode).
![image](https://user-images.githubusercontent.com/66315766/127630540-994225d3-9ea7-4f73-b845-c4e056017837.png)

   I used the reset function provided by Pyfmi package, but it failed. And the error is as follows.
![image](https://user-images.githubusercontent.com/66315766/127630494-e195b4b3-3204-4d7a-a747-9b2e82d03a62.png)

**Comment by lochel** [comment]
Do you reset the FMU on the first iteration before it was initialized?

**Comment by xifanghnu** [comment]
No,  I don't reset the FMU on the first iteration. I reset it on the second iteration afer it was initialized.
![image](https://user-images.githubusercontent.com/66315766/127643904-79d2844c-6b7b-4b55-be0a-76da85ab13e6.png)

**Comment by chria** [comment]
What does the log say?

**Comment by xifanghnu** [comment]
> Do you reset the FMU on the first iteration before it was initialized?

No, I don't reset the FMU on the first iteration. I reset it on the second iteration afer it was initialized.
![image](https://user-images.githubusercontent.com/66315766/127765360-ab274b20-75a2-486e-a06c-c6688d8d6d27.png)

**Comment by xifanghnu** [comment]
@chria The log doesn't show any error information.

**Comment by xifanghnu** [comment]
And I find a strange phenomenon. The program running error shows that there exist a fmi.pyx file, while my PyFMI package only have a fmi.py file but not a fmi.pyx file. And I find the content of Line 4638 shown in the error is not consist with  my pyfmi.fmi.FMUModelBase2.reset function. Also the fmi.py file in my PyFMI package doesn't include the FMUModelME1, FMUModelME2, FMUModelCS1, FMUModelCS2 class. But a file fmi.py in another file path include these classes, and the programm seems to call this fmi.py file. This really makes me confused. 
![image](https://user-images.githubusercontent.com/66315766/127857008-45efce53-4dd0-41ac-b7ea-b1f0bb95b131.png)
The called fmi.py file is not in the PyFMI package path, but in the following file path.
![image](https://user-images.githubusercontent.com/66315766/127857112-6492b3b2-be77-4dd5-b749-2d2ca942af7f.png)

**Comment by chria** [comment]
I recommend to increase the log level (i.e. something like, "model = load_fmu(..., log_level=6)" and then look at the log files. This is not a problem in PyFMI but in the FMUs that you are using.
