### ISSUE TITLE
JModelica with spyder

### ISSUE THREAD

**Issue by kosmylo** [modelon-community/PyFMI#118]
I have installed successfully jmodelica and I have tested it through jupyter notebook. However, when I am trying to do the same procedure, but then open spyder I am getting an error.

Specifically, what I am doing is the following:

open anaconda terminal

activate my environment in which spyder is installed

run setenv.bat 64

spyder

I am getting the following error:

```
Fatal Python error: initfsencoding: unable to load the file system codec
  File "C:\JModelica.org-2.4\\Python27\Python_64\lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax
```

Any idea of what is going on?

**Comment by chria** [comment]
This is unfortunately not related to PyFMI.
