### ISSUE TITLE
FMU: Windows to Linux

### ISSUE THREAD

**Issue by samiit** [modelon-community/PyFMI#131]
Hi,

I would like to export an FMU from Matlab/Simulink installed in Windows, that I can then run using Python installed on Ubuntu 20. What should be the procedure to export the FMU from a Windows machine?

Thanks,
Sam

**Comment by modelonrobinandersson** [comment]
@samiit You would need to export the FMU using the tool (Matlab/Simulink) such that it is compatible for the platform you want to run it on. I suggest you contact the support for the tool you are using. If the FMU is exported for Ubuntu 20 you will be able to run it using PyFMI on Ubuntu 20, assuming you have installed PyFMI on your target platform.
