### ISSUE TITLE
Realtime simulation

### ISSUE THREAD

**Issue by Krokos11** [modelon-community/PyFMI#132]
Is there any way to run the simulation in realtime? I want to be able to run the simulation and change the inputs while it is running. If there is such a possibility, someone could provide an example of how to do it. How should the fmu model be constructed, is it necessary to do it in some special way. How to run simulation in realtime mode from python? How to change its inputs during the simulation?

Thank you in advance for your answer.

**Comment by modelonrobinandersson** [comment]
Hi @Krokos11, a new option for realtime simulation was added  in PyFMI 2.9.7, see https://github.com/modelon-community/PyFMI/commit/9de8e4f76e4a746949286f9dae29550f71627577.
