### ISSUE TITLE
SuperLU missing in latest pyfmi on conda forge?

### ISSUE THREAD

**Issue by dhblum** [modelon-community/PyFMI#133]
I've compiled a relatively complex ME FMU of a model from the [Modelica Buildings Library](https://simulationresearch.lbl.gov/modelica/) v8.1.0: [Buildings.Examples.VAVReheat.Validation.TraceSubstance](https://simulationresearch.lbl.gov/modelica/releases/v8.1.0/help/Buildings_Examples_VAVReheat_Validation.html#Buildings.Examples.VAVReheat.Validation.TraceSubstance).

I'm working on Ubuntu 18.04 and have conducted the following tests with the FMU compiled by both Optimica and JModelica and gotten the same results.  

When I use ``$ conda install -c conda-forge pyfmi`` in a Python 3.10 environment and write a Python script to load and simulate the FMU with CVODE from t=0 to 86400, I get the following error:

```
$ python simulate_fmu.py
Traceback (most recent call last):
  File "/home/userX/simulate_fmu.py", line 7, in <module>
    res = model.simulate(0,86400, options=options)
  File "src/pyfmi/fmi.pyx", line 8125, in pyfmi.fmi.FMUModelME2.simulate
  File "src/pyfmi/fmi.pyx", line 378, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "src/pyfmi/fmi.pyx", line 374, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "/home/userX/miniconda3/envs/pyfmi_conda_20220201/lib/python3.10/site-packages/pyfmi/fmi_algorithm_drivers.py", line 703, in solve
    self.simulator.simulate(self.final_time, self.ncp)
  File "assimulo/ode.pyx", line 180, in assimulo.ode.ODE.simulate
  File "assimulo/ode.pyx", line 300, in assimulo.ode.ODE.simulate
  File "assimulo/explicit_ode.pyx", line 101, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/explicit_ode.pyx", line 188, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/solvers/sundials.pyx", line 1935, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 1950, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 2194, in assimulo.solvers.sundials.CVode.initialize_options
assimulo.exception.AssimuloException: No support for SuperLU was detected, please verify that SuperLU and SUNDIALS has been installed correctly.
```

When I use ``$ conda install -c conda-forge/label/gcc7 pyfmi`` in a Python 3.7 environment (needed for gcc7) and do the same as above, it simulates OK.  Unfortunately, this is an old version of pyfmi and Python.  

Note the FMU simulates OK with the Optimica and JModelica installations.

Does the latest version of pyfmi from conda forge install Sundials properly with SuperLU?

**Comment by modelonrobinandersson** [comment]
@dhblum can you see what version of assimulo that is in your environment? Sundials is a build dependency for Assimulo, which in turn is a dependency for PyFMI.

**Comment by dhblum** [comment]
Thanks @modelonrobinandersson.  Using the command ``conda install -c conda-forge pyfmi`` it looks like the version of Assimulo is 3.2.9.  

I know when building pyfmi from sources, I need to specify the option in the Sundials build to include SuperLU and also include the options in the Assimulo build that says Sundials includes SuperLU.

**Comment by modelonrobinandersson** [comment]
If I understand you correctly @dhblum, when you install PyFMI via conda, it also installs Assimulo for you? Which I assume since its a mandatory dependency. If this is the case I assume that the assimulo that is being installed is not built properly.  
PyFMI does not depend on sundials nor superlu but assimulo does. When you build Assimulo from source both sundials and superlu can be specified, i.e. if you look in setup.py in the assimulo source, you have the options for blas, lapack, sundials and superlu.

**Comment by dhblum** [comment]
Yes, when you use ``conda install -c conda-forge pyfmi`` it installs Assimulo for you.  If the Assimulo being installed is not built properly, can that be fixed?

**Comment by modelonrobinandersson** [comment]
@dhblum I need to get in contact with the person who makes these available via conda first. 
On a side-note I think the documentation for building and installing assimulo needs an update since there seems to be many people who experience difficulties with this (which in turn affects PyFMI).

**Comment by dhblum** [comment]
Ok sounds good, thanks for your attention.

And yes, I remember it taking some time to figure out the building and installing of assimulo.  Though some of that may have also been because I needed to figure out how to build/install the dependencies as well.

**Comment by jschueller** [comment]
could you provide the script to reproduce the issue ?

**Comment by jschueller** [comment]
ping @dhblum

**Comment by dhblum** [comment]
Thank you! @jschueller 

Install conda and then install pyfmi using:

```
$ conda create --name pyfmi_latest python=3.10
$ conda activate pyfmi_latest
```
Then, compile the FMU using the attached ``compile_fmu.py`` with JModelica (you'll need to edit full path to your Buildings Library v8.1).  Unfortunately, I can't upload the FMU to this comment. 

Then, run with the attached ``simulate_fmu.py`` and ``Buildings_Examples_VAVReheat_Validation_TraceSubstance.fmu``:
```
$ python simulate_fmu.py
```

The output I get is:
```~$ python simulate_fmu.py 
Traceback (most recent call last):
  File "/home/dhbubu18/simulate_fmu.py", line 9, in <module>
    res = model.simulate(start_time,final_time,options=options)
  File "src/pyfmi/fmi.pyx", line 8224, in pyfmi.fmi.FMUModelME2.simulate
  File "src/pyfmi/fmi.pyx", line 378, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "src/pyfmi/fmi.pyx", line 374, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "/home/dhbubu18/miniconda3/envs/pyfmi_latest/lib/python3.10/site-packages/pyfmi/fmi_algorithm_drivers.py", line 802, in solve
    self.simulator.simulate(self.final_time, self.ncp)
  File "assimulo/ode.pyx", line 185, in assimulo.ode.ODE.simulate
  File "assimulo/ode.pyx", line 308, in assimulo.ode.ODE.simulate
  File "assimulo/explicit_ode.pyx", line 135, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/explicit_ode.pyx", line 221, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/solvers/sundials.pyx", line 2050, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 2065, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 2359, in assimulo.solvers.sundials.CVode.initialize_options
assimulo.exception.AssimuloException: No support for SuperLU was detected, please verify that SuperLU and SUNDIALS has been installed correctly
```
This is tested with Ubuntu18.

[compile_fmu.txt](https://github.com/modelon-community/PyFMI/files/11834969/compile_fmu.txt)

[simulate_fmu.txt](https://github.com/modelon-community/PyFMI/files/11834970/simulate_fmu.txt)

**Comment by jschueller** [comment]
could you upload the fmu somewhere ? I dont have jmodelica

**Comment by jschueller** [comment]
hi @dhblum can you retry with the latest assimulo ?

**Comment by dhblum** [comment]
@jschueller I've created a new repo and added the FMU here: https://github.com/dhblum/SampleFMU.  It was compiled on Ubuntu 18 using JModelica.

Regarding your last comment, can I specify what version of assimulo is used when running ``$ conda install -c conda-forge pyfmi``?

**Comment by jschueller** [comment]
yes, try conda install assimulo=3.4.1

**Comment by dhblum** [comment]
``conda install assimulo=3.4.1`` didn't work:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - assimulo=3.4.1

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

I tried ``conda install -c conda-forge assimulo``, which yielded:

```
The following packages will be UPDATED:

  assimulo                              3.4-py310he081083_0 --> 3.4-py310h48d6207_1
```

When I check the package version it still reads 3.4.0.   But I tried simulating the FMU again with this and got the same error about no support for SuperLU.

**Comment by dhblum** [comment]
I don't see assimulo 3.4.1 available on conda? https://anaconda.org/conda-forge/assimulo/files.

**Comment by jschueller** [comment]
oh, indeed, the update did not go thought as I thought, should be ok now

**Comment by dhblum** [comment]
Ok, I again ran ``conda install -c conda-forge assimulo``, which yielded:

```
The following packages will be UPDATED:

  assimulo                              3.4-py310h48d6207_1 --> 3.4.1-py310h48d6207_0
```

So seems like it updated to 3.4.1.

Then I ran ``simulate_fmu.py`` again to simulate the FMU.  Unfortunately, I tried to simulate the fmu and got the same SuperLU support error.

**Comment by jschueller** [comment]
I see, superlu must be enabled at both sundials & assimulo levels, can you retry with sundials-6.5.1-h777d08e_1 ?

**Comment by dhblum** [comment]
I ran ``conda install -c conda-forge sundials``, which yielded:
```
The following packages will be UPDATED:

  openssl               pkgs/main::openssl-3.0.9-h7f8727e_0 --> conda-forge::openssl-3.1.1-hd590300_1
  sundials                                 6.5.1-h6250759_0 --> 6.5.1-h777d08e_1
```
I then tried to simulate the FMU and got the same SuperLU support issue.

**Comment by PeterMeisrimelModelon** [comment]
Can you try a clean re-install of assimulo, then PyFMI? I recall seeing this issue once when updating Assimulo, but not PyFMI.

**Comment by jschueller** [comment]
It should be ok now, I fixed one more issue in the sundials package

**Comment by dhblum** [comment]
Aha it worked!  Thank you @jschueller!  Just to confirm, I ran:

```
$ conda create --name pyfmi_latest python=3.10
$ conda activate pyfmi_latest
$ conda install -c conda-forge pyfmi
$ python simulate_fmu.py
```
And got:
```
Final Run Statistics: --- e+04

 Number of steps                                 : 7024
 Number of function evaluations                  : 14504
 Number of Jacobian evaluations                  : 906
 Number of function eval. due to Jacobian eval.  : 0
 Number of error test failures                   : 360
 Number of nonlinear iterations                  : 12294
 Number of nonlinear convergence failures        : 184
 Number of state function evaluations            : 7898
 Number of state events                          : 16
 Number of time events                           : 720

Solver options:

 Solver                   : CVode
 Linear multistep method  : BDF
 Nonlinear solver         : Newton
 Linear solver type       : SPARSE
 Maximal order            : 5
 Tolerances (absolute)    : [1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-08 2.9315e-06 2.9315e-06 3.0000e-06 3.0000e-06 3.0000e-06
 3.0000e-06 3.0000e-06 3.0000e-06 2.9315e-06 2.9315e-06 2.9315e-06
 2.9315e-06 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06 2.9315e-06
 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06
 1.0000e-08 1.0000e-03 1.0000e-08 1.0000e-08 2.9315e-06 2.9315e-06
 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06
 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06 3.0000e-06 3.0000e-06
 3.0000e-06 3.0000e-06 2.9315e-06 2.9315e-06 2.9315e-06 1.0000e-03
 1.0000e-08 1.0000e-08 2.9315e-06 2.9315e-06 3.0000e-06 3.0000e-06
 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06 2.9315e-06 2.9315e-06
 2.9315e-06 2.9315e-06 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06
 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06
 2.9315e-06 1.0000e-03 1.0000e-08 1.0000e-08 2.9315e-06 2.9315e-06
 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06 3.0000e-06
 2.9315e-06 2.9315e-06 2.9315e-06 2.9315e-06 3.0000e-06 3.0000e-06
 3.0000e-06 3.0000e-06 2.9315e-06 2.9315e-06 2.9315e-06 1.0000e-03
 1.0000e-08 1.0000e-08 2.9315e-06 2.9315e-06 2.9315e-06 3.0000e-06
 3.0000e-06 3.0000e-06 3.0000e-06 2.9315e-06 1.0000e-03 1.0000e-08
 1.0000e-08 3.0000e-06 1.0000e-03 1.0000e-08 1.0000e-08 1.0000e-03
 1.0000e-08 3.0000e-06 1.0000e-03 1.0000e-08 1.0000e-03 1.0000e-08
 3.0000e-06 1.0000e-03 1.0000e-08 1.0000e-03 1.0000e-08 3.0000e-06
 1.0000e-03 1.0000e-08 1.0000e-03 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-03 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-08
 1.0000e-08 1.0000e-08 1.0000e-08 1.0000e-03 1.0000e-03 1.0000e-03
 1.0000e-03 1.0000e-08 1.0000e-08]
 Tolerances (relative)    : 1e-06

Simulation interval    : 0.0 - 86400.0 seconds.
Elapsed simulation time: 10.522079802000007 seconds.
```

**Comment by jschueller** [comment]
glad it worked, could you close the issue ?

**Comment by dhblum** [comment]
Closing given confirmation above.

**Comment by testcan** [comment]
Hello all, 

I am getting the same issue if i try to run cvode_basic.py example with  Linear solver type       : SPARSE. 
The error message is the following:  assimulo.exception.AssimuloException: No support for SuperLU was detected, please verify that SuperLU and SUNDIALS has been installed correctly.

I follow the steps suggested by @dhblum but didnt work for me.

Here I report the version installed in my conda enviroment:
assimulo                  3.4.1           py310h9e5cad0_3    conda-forge
sundials                  6.5.1                h63175ca_3    conda-forge
pyfmi                     2.11.0          py310h9b08ddd_0    conda-forge

Thank you in advance for any help.

**Comment by jschueller** [comment]
@testcan it would help to provide the script that reproduces the error

**Comment by testcan** [comment]
Here it is:, I am sorry for the format. I am using Windows10 and anaconda on Windows.
If i change the linear_solver to 'DENSE' it works fine, but i need to use sparse sincei have a complex matrix and i need to save computational time.
Thanks a lot for any help.

"""" HERE THE CODE
`import numpy as N
#import pylab as P
import nose
from assimulo.solvers import CVode
from assimulo.problem import Explicit_Problem

def run_example(with_plots=True):
    # Define the rhs
    def f(t, y):
        ydot = -y[0]
        return N.array([ydot])

    # Define an Assimulo problem
    exp_mod = Explicit_Problem(f, y0=4, name=r'CVode Test Example: $\dot y = - y$')

    # Define an explicit solver
    exp_sim = CVode(exp_mod)  # Create a CVode solver

    # Sets the parameters
    exp_sim.iter = 'BDF'  # Default 'FixedPoint'
    exp_sim.discr = 'Adams'  # Default 'Adams'
    exp_sim.atol = [1e-4]  # Default 1e-6
    exp_sim.rtol = 1e-4  # Default 1e-6
    exp_sim.linear_solver='SPARSE'
    # Simulate
    t1, y1 = exp_sim.simulate(5, 100)  # Simulate 5 seconds
    t2, y2 = exp_sim.simulate(7)  # Simulate 2 seconds more

    # Basic test
    nose.tools.assert_almost_equal(float(y2[-1]), 0.00347746, 5)
    nose.tools.assert_almost_equal(exp_sim.get_last_step(), 0.0222169642893, 3)

    # Plot
    if with_plots:
        P.plot(t1, y1, color="b")
        P.plot(t2, y2, color="r")
        P.title(exp_mod.name)
        P.ylabel('y')
        P.xlabel('Time')
        P.show()
    return exp_mod, exp_sim


if __name__ == '__main__':
    mod, sim = run_example()'
