### ISSUE TITLE
pyFMI installation issues

### ISSUE THREAD

**Issue by NikolaH1** [modelon-community/PyFMI#14]
Installing pyFMI with Conda gives the following error:
import pyfmi
pyfmi.check_packages()

Performing pyfmi package check 
==============================

Could not find cannot import name 'radau5'
Could not find cannot import name 'dopri5'
Could not find cannot import name 'rodas'
Could not find cannot import name 'odassl'
Could not find ODEPACK functions.
Could not find RADAR5
Could not find GLIMDA.
PyFMI version ................ 2.5                           

Platform ..................... win32                         

Python version ............... 3.6.8                         

Dependencies: 

Package                        Version                       
-------                        -------                       
assimulo...................... 3.0                           
Cython........................ 0.29.6                        
lxml.......................... 4.3.0                         
matplotlib.................... 3.0.2                         
numpy......................... 1.16.2                        
scipy......................... 1.2.1                         
wxPython...................... --              Package missing - Warning issued, see details below
pyreadline.................... 2.1                           
setuptools.................... 40.8.0                        

Warnings 
--------

-- The package wxPython could not be found. This package is needed to be able to use the plot-GUI.

I can't figure it out what is causing the error! With conda installation the assimulo is installed together with pyFMI

**Comment by NikolaH1** [comment]
When I try to simulate my model i get an error:


CVodeError: {-1: 'The solver took max internal steps but could not reach tout.', -2: 'The solver could not satisfy the accuracy demanded by the user for some internal step.', -3: 'Error test failures occurred too many times during one internal time step or minimum step size was reached.', -4: 'Convergence test failures occurred too many times during one internal time step or minimum step size was reached.', -5: 'The linear solvers initialization function failed.', -6: 'The linear solvers setup function failed in an unrecoverable manner.', -7: 'The linear solvers solve function failed in an unrecoverable manner.', -8: 'The user-provided rhs function failed in an unrecoverable manner.', -9: 'The right-hand side function failed at the first call.', -10: 'The right-hand side function had repeated recoverable errors.', -11: 'The right-hand side function had a recoverable error, but no recovery is possible.', -12: 'The rootfinding function failed in an unrecoverable manner.', -20: 'A memory allocation failed.', -21: 'The cvode_mem argument was NULL.', -22: 'One of the function inputs is illegal.', -23: 'The CVode memory block was not allocated by a call to CVodeMalloc.', -24: 'The derivative order k is larger than the order used.', -25: 'The time t is outside the last step taken.', -26: 'The output derivative vector is NULL.', -27: 'The output and initial times are too close to each other.', -41: 'The sensitivity right-hand side function failed unrecoverable.'}

**Comment by giplessis** [comment]
> 
> 
> Installing pyFMI with Conda gives the following error:
> import pyfmi
> pyfmi.check_packages()
> # Performing pyfmi package check
> 
> Could not find cannot import name 'radau5'
> Could not find cannot import name 'dopri5'
> Could not find cannot import name 'rodas'
> Could not find cannot import name 'odassl'
> Could not find ODEPACK functions.
> Could not find RADAR5
> Could not find GLIMDA.
> I can't figure it out what is causing the error! With conda installation the assimulo is installed together with pyFMI

Installation performed with conda , Python 3.8 and similar issue of solvers not found from Assimulo. 
Maybe similar to : https://github.com/conda-forge/assimulo-feedstock/issues/19
Any new/hint on this?

**Comment by modelonrobinandersson** [comment]
Hi @NikolaH1, sorry for the lack of replies. Is this still an issue for you? The error you are seeing is not due to PyFMI but is because of your Assimulo installation. It seems that you have an assimulo installed that was not built with its proper dependencies. I will close this issue for now but feel free to open it up if this issue remains active today.
