### ISSUE TITLE
FMUModelBase2.(de)serialize_fmu_state() raises undocumented NotImplementedError

### ISSUE THREAD

**Issue by MissingShoes** [modelon-community/PyFMI#15]
Hi,

I just realized, that `FMUModelBase2.serialize_fmu_state()` and `FMUModelBase2.deserialize_fmu_state()` raise `NotImplementedError`s (although there seems to be some kind of implementation for the methods). This means that it is impossible to save the state of a FMU to disk or to re-use it after reloading a model later in a program. It would be great if this would be stated in the documentation in order to avoid bad surprises in projects like mine, whose implementation rely on this FMU2.0 functionality.

**Comment by chria** [comment]
In the latest version of PyFMI, this is now fixed.
