### ISSUE TITLE
Importing MatFile4Reader from scipy.io.matlab module throws an error

### ISSUE THREAD

**Issue by jakub-a-wysocki** [modelon-community/PyFMI#153]
PR #147 introduced conditional import of `MatFile4Reader` from `scipy.io.matlab`:
`from scipy.io.matlab import MatFile4Reader, VarReader4, convert_dtypes, mdtypes_template, mxSPARSE_CLASS`

Because of this, when `scipy` >= 1.8 is used, the following error is thrown:

```
ImportError: cannot import name 'MatFile4Reader' from 'scipy.io.matlab' (...\scipy\io\matlab\__init__.py)
```

As per [Issue #15716](https://github.com/scipy/scipy/issues/15716) from SciPy repo, this import should be replaced by `scipy.io.loadmat`.

**Comment by modelonrobinandersson** [comment]
@jakub-a-wysocki When I try to import `MatFile4Reader` from `scipy.io.loadmat` I get a `ModuleNotFoundError`. Have you successfully imported this? What version of scipy are you using? I have tested this with version `1.8.0`.  

`In [1]: import scipy  
  
In [2]: scipy.__version__  
Out[2]: '1.8.0'  
In [3]: from scipy.io.loadmat import MatFile4Reader  
---------------------------------------------------------------------------  
ModuleNotFoundError                       Traceback (most recent call last)  
<ipython-input-4-b877e4e3f62b> in <module>  
----> 1 from scipy.io.loadmat import MatFile4Reader  
  
ModuleNotFoundError: No module named 'scipy.io.loadmat'`

**Comment by jakub-a-wysocki** [comment]
`scipy.io.loadmat` is not a module, but a function. I think that the idea from SciPy developers is that instead of importing objects from modules in `scipy.io.matlab` module only public objects defined in `scipy.io` should be used. I guess that it could be very problematic to rewrite the code to use only objects from `scipy.io`, so instead importing from `scipy.io.matlab.mio4` needed objects can be imported from `scipy.io.matlab._mio4` module - then no warning would be thrown.

See [issue 14360](https://github.com/scipy/scipy/issues/14360) and [PR 15084](https://github.com/scipy/scipy/pull/15084) in SciPy repo for more more information.

**Comment by modelonrobinandersson** [comment]
@jakub-a-wysocki  thank you. I have created https://github.com/modelon-community/PyFMI/pull/154.
