### ISSUE TITLE
Build fmi-library on Ubuntu linux 

### ISSUE THREAD

**Issue by Nilswaap-dot** [modelon-community/PyFMI#162]
Hi, 

I am trying to build the fmi-libary as it's shown in the README:
\code
	mkdir build-fmil; cd build-fmil
	cmake -DFMILIB_INSTALL_PREFIX=<prefix> <path to FMIL source>
	make install test
\endcode

After creating the directory and entering it, I write the following code to build it:
cmake -DFMILIB_INSTALL_PREFIX=<prefix> /home/arbeit/Downloads/FMILibrary-2.0/src
bash: prefix: No such file or directory

It says there is no such file or directory. And no matter how many times I change the path, it is always saying there is no such file or directory. I tried different variations of the path and it always comes out to the same.

Hope you have an Idea.

Kind regards
Nils

**Comment by PeterMeisrimelModelon** [comment]
In

cmake -DFMILIB_INSTALL_PREFIX= /home/arbeit/Downloads/FMILibrary-2.0/src 

there appears to be a space after "=", try removing it.

**Comment by PeterMeisrimelModelon** [comment]
Any updates @Nilswaap-dot , did this resolve the issue?

**Comment by Nilswaap-dot** [comment]
> Any updates @Nilswaap-dot , did this resolve the issue?

Yes @PeterMeisrimelModelon 
It worked perfectly. 

Thank you!
