### ISSUE TITLE
Issue during import of pyfmi

### ISSUE THREAD

**Issue by alelurgo** [modelon-community/PyFMI#17]
Hi there,

I will be using pyfmi to couple the multibody software Adams with a CFD code. 
I have downloaded this pyfmi version for Windows:
win-64/pyfmi-2.5.3-py36hc8d92b1_0.tar.bz2
I am using Spyder with Python 3.6
I got the following error message when I type **import pyfmi**
---------------------------------------------------------------------------------
import pyfmi
Traceback (most recent call last):

  File "<ipython-input-8-df481fa81f2d>", line 1, in <module>
    import pyfmi

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyfmi\__init__.py", line 24, in <module>
    from .fmi import FMUModel, load_fmu, FMUModelME1, FMUModelME2

  File "src\pyfmi\fmi.pyx", line 37, in init pyfmi.fmi

  File "__init__.pxd", line 1038, in numpy.import_array

ImportError: numpy.core.multiarray failed to import
---------------------------------------------------------------------------------
numpy version that I have installed is 1.12.0

I don't have any clue how to get pyfmi work. Thanks

**Comment by modelonrobinandersson** [comment]
Hi @alelurgo, there seems to be an issue with your environment. See https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import
