### ISSUE TITLE
SuperLU Error after conda installation

### ISSUE THREAD

**Issue by testcan** [modelon-community/PyFMI#194]
Hello all, 

I am getting the same issue if i try to run cvode_basic.py example with  Linear solver type       : SPARSE. 
The error message is the following:  assimulo.exception.AssimuloException: No support for SuperLU was detected, please verify that SuperLU and SUNDIALS has been installed correctly.

I follow the steps suggested by @dhblum but didnt work for me.

Here I report the version installed in my conda enviroment:
assimulo                  3.4.1           py310h9e5cad0_3    conda-forge
sundials                  6.5.1                h63175ca_3    conda-forge
pyfmi                     2.11.0          py310h9b08ddd_0    conda-forge

Thank you in advance for any help.

_Originally posted by @testcan in https://github.com/modelon-community/PyFMI/issues/133#issuecomment-1644384597_

**Comment by jschueller** [comment]
could you update everything and retry ?

**Comment by testcan** [comment]
Hi,

I updated everything with the command: `conda update --all`

I checked the list of packages with : `conda list`:
Here below the summary in case it helps:

assimulo                  3.4.1           py310h9e5cad0_3    conda-forge
sundials                  6.5.1                h63175ca_3    conda-forge
pyfmi                     2.11.0          py310h9b08ddd_0    conda-forge
python                    3.10.12         h4de0772_0_cpython    conda-forge

I re-run the code but I still get the same error:
assimulo.exception.AssimuloException: No support for SuperLU was detected, please verify that SuperLU and SUNDIALS has been installed correctly.

Thanks in advance for any help,

**Comment by jschueller** [comment]
there should be a new assimulo package, maybe wait an hour or two and retry, or grab it directly:
https://anaconda.org/conda-forge/assimulo/files

**Comment by modelonrobinandersson** [comment]
@testcan is this still an issue or is it resolved?

**Comment by testcan** [comment]
Hello! Thank you all! it worked perfectly thanks a lot!
