### ISSUE TITLE
PyFMI-2.11.0 tag

### ISSUE THREAD

**Issue by siegLoesch** [modelon-community/PyFMI#197]
The last release of PyFMI has no tag. Calling this tag on github shows the following warning:
**This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.**
Also a the command _git tag --list_ yields no PyFMI-2.11.0 tag.
A correction of that circumstance would be welcome to keep available scripts running.

Best regards
Siegfried

**Comment by PeterMeisrimelModelon** [comment]
The "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." should be fixed now.

However, the tag should have been visible via _git tag --list_ either way. Maybe you need to run _git fetch --tags_ ?

**Comment by siegLoesch** [comment]
That worked fine - thank you! after _git pull_ the tag can be correctly listed.
Best regards
Siegfried
