### ISSUE TITLE
Varying Modelica parameters with "model.set"

### ISSUE THREAD

**Issue by Paolini408** [modelon-community/PyFMI#201]
Hi,
I extracted a FMU file from OpenModelica of a RC model of a building (Building Library). When I use "model.set" I can only change some parameters as thermal resistances R or heat capacities C, but I can not change the Areas and the Volume. The variables are well-defined on OpenModelica and I manage to run many simulations with different values of A [m2] and V [m3].

Thank you.

**Comment by PeterMeisrimelModelon** [comment]
Do you get an error or what happens when you use `model.set` for these variables?

**Comment by Paolini408** [comment]
I don't get an error and the simulation runs correctly on PyCharm. The problem is that "model.set" doesn't modify the values of certain parameters and the simulation results remain unchanged from the default values set in OpenModelica. Instead, for other parameters like thermal resistances and heat capacities, I observe distinct simulation results when using PyCharm.

**Comment by PeterMeisrimelModelon** [comment]
Are you setting the parameters before or after initialization? They could be calculated parameters, set during initialization, which would overwrite your manual adjustments before initialization.

**Comment by Paolini408** [comment]
I show you a part of my code:

> model_building = load_fmu('Building.fmu')
> model_building.reset()
> 
> opts_building = model_building.simulate_options()
> opts_building['ncp'] = 3
> opts_building['initialize'] = True
> 
> model_building.set('RC_model.VAir', 16452)  #It doesn't work
> model_building.set('A_extwall[1]', [427])  #It doesn't work
> model_building.set('A_roof', 2742)  #It doesn't work
> 
> model_building.set('U_window', 3.8)  #It works
> model_building.set('R_roof[1]', [0.000255])  #It works
> model_building.set('C_extwall[1]', [2695463])  #It works

**Comment by PeterMeisrimelModelon** [comment]
I'm assuming there is some 

`res = model_building.simulate(options = opts_building)`

line after that and you observe an incorrect result after that.

Try to instead do 

```
model_building = load_fmu('Building.fmu')
model_building.reset()

opts_building = model_building.simulate_options()
opts_building['ncp'] = 3
opts_building['initialize'] = False

model_building.initialize()

model_building.set('RC_model.VAir', 16452) #It doesn't work
model_building.set('A_extwall[1]', [427]) #It doesn't work
model_building.set('A_roof', 2742) #It doesn't work

model_building.set('U_window', 3.8) #It works
model_building.set('R_roof[1]', [0.000255]) #It works
model_building.set('C_extwall[1]', [2695463]) #It works

#....
res = model_building.simulate(options = opts_building)
```

**Comment by Paolini408** [comment]
I get this error: 'The right-hand side function had repeated recoverable errors. At time 1.776974.'

Continuing with my original code::
```
timestep = 900
simulation_length = 172800
index = 0

while index < simulation_length:
    res_building = model_building.simulate(start_time=index, final_time=index + timestep, options=opts_building)
    opts_building['initialize'] = False

#...
```

**Comment by PeterMeisrimelModelon** [comment]
This means the model failed to evaluate too often, for that you need to inspect the XML log from `model_building.extract_xml_log()` to see why it is failing. Note: Most of the contents of these will be generated by your model.

In your example it should be sufficient to simply execute

`res_building = model_building.simulate(start_time=0, final_time=simulation_length, options=opts_building)`

Unless you specifically want to perform various operations on the model in between different simulation windows. `model_building.simulate` automatically handles timestepping.

**Comment by Paolini408** [comment]
I use:
```
while index < simulation_length:
    res_building = model_building.simulate(start_time=index, final_time=index + timestep, options=opts_building)
    opts_building['initialize'] = False
```
because my goal is to perform various operations on the model between different simulation windows.

The simulation doesn't fail, but the parameters like Areas and Volume that I would like to modify remain the same and the results don't change. In addition, the XML file contains only this because I assume that the simulation finishes correctly:
```
<?xml version="1.0" encoding="UTF-8"?>
<JMILog category="info">
</JMILog>
```

**Comment by PeterMeisrimelModelon** [comment]
Can you share the FMU or at minimum its modelDescription.xml?

**Comment by Paolini408** [comment]
[FMU_file.zip](https://github.com/modelon-community/PyFMI/files/12859097/FMU_file.zip)

This FMU is obtained from the Buldings Library (`Buildings.ThermalZones.ReducedOrder.Examples`).

I don't manage to modify the geometric parameters (areas and volume) of the block `thermalZoneFourElements`, which is contained inside the example.

**Comment by PeterMeisrimelModelon** [comment]
Relevant parts from the `modelDescription.xml`

```
  <!-- Index of variable = "340" -->
  <ScalarVariable
    name="thermalZoneFourElements.VAir"
    valueReference="669"
    description="Air volume of the zone"
    variability="fixed"
    causality="**calculatedParameter**"
    >
    <Real unit="m3"/>
  </ScalarVariable>
```

Similarly, all `thermalZoneFourElements.A*` variables are also **calculatedParameter**s.

From the FMI2 specification:

```
"calculatedParameter": A data value that is constant during the simulation and
is computed during initialization or when tunable parameters change.
variability must be "fixed" or "tunable". initial must be "approx",
"calculated" or not present (meaning calculated).
```

I.e., these parameters are calculated during initialization and not changeable afterwards.

I'll consider this issue resolved, since any follow-up questions as to why these are calculated parameters or how to make a setup that allows changing them are either modelling questions or questions for the FMU generation tool - OpenModelica.
