### ISSUE TITLE
Provide compatibility information on the FMI tools page

### ISSUE THREAD

**Issue by chrbertsch** [modelon-community/PyFMI#202]
For the examplesURL you are encouraged to provide a link to a webpage or repo where you document how you tested your tool w.r.t to FMI support. See e.g. [https://github.com/altairengineering/fmus](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltairengineering%2Ffmus&data=05%7C01%7CChristian.Bertsch%40de.bosch.com%7C01cb7050c3044b3d2c2e08dbd1ac4020%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638334309952318885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7cblzvmoxG496WskCZUVcxnJzQU8aDUxkUDtydXdl2A%3D&reserved=0) for an example

This is especially important for PyFMI, as other tools depend on your implementation, see e.g. https://github.com/openturns/otfmi/issues/97

Thanks in advance!

**Comment by modelonrobinandersson** [comment]
Hi @chrbertsch, thank you for raising this. I will see what I can do and get this fixed.

**Comment by modelonrobinandersson** [comment]
Hi @chrbertsch, is it required to upload actual FMUs used for testing or does it suffice to simply document how the tool has been tested?

**Comment by chrbertsch** [comment]
> Hi @chrbertsch, is it required to upload actual FMUs used for testing or does it suffice to simply document how the tool has been tested?

Especially as an importing tool you do not have to upload the FMUs with which you have tested your import. You can just describe it. If the FMUs are publicly available (e.g. the Reference FMUs, FMUs form the old Cross-Check or FMUs provided by other exporting tools from providing "compatibility information")  you  should reference or link them.

Thanks!

**Comment by modelonrobinandersson** [comment]
Hi @chrbertsch, I am closing this issue as I have opened https://github.com/modelon-community/PyFMI/pull/204.
Feel free to reopen this if it is not properly documented yet.
