### ISSUE TITLE
Error on loading unzipped fmu

### ISSUE THREAD

**Issue by coolermzb3** [modelon-community/PyFMI#208]
### environment
- win11 
- python=3.11
- pyfmi=2.11.0 (latest from conda-forge)
- CoSimulation model fmiVersion=2
### issue
When I execute `pyfmi.loadfmu("myfmu.fmu")`, everything works as expected.
Howerver, when I unzip the fmu to "myfmu" and run `pyfmi.loadfmu("myfmu", allow_unzipped_fmu=True)`, I encounter the following error:
```
File src\pyfmi\fmi.pyx:8822, in pyfmi.fmi.load_fmu()
File src\pyfmi\fmi.pyx:7062, in pyfmi.fmi.FMUModelCS2.__init__()
File src\pyfmi\fmi.pyx:4169, in pyfmi.fmi.FMUModelBase2.__init__()
InvalidBinaryException: The FMU could not be loaded. Error loading the binary. Could not load the FMU binary: �Ҳ���ָ����ģ�顣
```
please note the "�Ҳ���ָ����ģ�顣", which remains **unchanged** regardless of my modifications to the foldername, the dll name or the modelIdentifier in xml file.
I've delved into [`fmi.pyx`](https://github.com/modelon-community/PyFMI/blob/master/src/pyfmi/fmi.pyx) but found no issues. Based on the code, it should work properly. 
My unzipped fmu is approximately 100MB in size. I've also tested with [a smaller fmu](https://github.com/semahal/FMU-Env/blob/master/InvertedPendulum_0FMU_Model_InvertedPendulum_0v2.fmu) which triggers the same error on my machine, with exactly the same error message. 

Noticing that direct loadfmu works fine, and it unzips the fmu file to a temp directory, I've compared the SHA256 values of the fmu in the temp directory and the one I unzipped myself, and they are identical.

It's entirely possible that I may have overlooked something or made an error, so any guidance would be appreciated.

**Comment by PeterMeisrimelModelon** [comment]
I can reproduce similar issue and we are looking into it.

Based on existing tests that do work, you can try the following:

```
from pyfmi import load_fmu
from pyfmi.common.core import create_temp_dir
from zipfile import ZipFile

fmu_name = <path/to/your/fmu>

fmu_dir = create_temp_dir()
with ZipFile(fmu_name, 'r') as fmu_zip:
    fmu_zip.extractall(path = fmu_dir)

fmu = load_fmu(fmu_dir, allow_unzipped_fmu = True)

# ...
```

**Comment by PeterMeisrimelModelon** [comment]
It does not appear to work with relative paths, but 

```
# ...
import os
fmu = load_fmu(os.path.abspath(fmu_dir), allow_unzipped_fmu = True)
```

should work.

**Comment by coolermzb3** [comment]
Thank you for your prompt and effective solution! It works!

This issue seems to be relatively straightforward to resolve, perhaps just by adding `fmu_temp_dir = os.path.abspath(fmu_temp_dir)` after line 1383 and 4106 in `fmi.pyx`. However, I find it challenging to build the library from source (to pass the tests), so I won't be submitting a PR.

I'll keep the issue open for now, and it can be closed once someone (or you) has fixed it. Once again, thank you for your invaluable assistance!

> It does not appear to work with relative paths, but
> 
> ```
> # ...
> import os
> fmu = load_fmu(os.path.abspath(fmu_dir), allow_unzipped_fmu = True)
> ```
> 
> should work.

**Comment by PeterMeisrimelModelon** [comment]
Fixed in https://github.com/modelon-community/PyFMI/pull/254.
