### ISSUE TITLE
Getter call not respecting variable type

### ISSUE THREAD

**Issue by fcollonval** [modelon-community/PyFMI#21]
Hey,

Working on a python fmu wrapper (https://github.com/NTNU-IHB/PythonFMU/pull/30). We discovered what seems to be a bug in PyFMI. The getter method used do not respect the variable type:

https://github.com/modelon-community/PyFMI/blob/df8228d4d97cfde3cd3fc321a4f3da31b417d4be/src/pyfmi/fmi_util.pyx#L312

As “valueReference” might not be unique for all variables, we think this is a bug in `PyFMI` rather than a feature that need to be supported.

A dirty fix could be:
```python
data = np.append(np.append(np.append(model.time, model.get_real(param_real)),model.get_integer(param_int)),model.get_boolean(param_bool))
```

But this may impact the creation of a efficient numpy array.

Note: The recorder of FMPy has a nice implementation for handling the getters - https://github.com/CATIA-Systems/FMPy/blob/d6f042a47d3725cdbdd87aeb4f87d28d290f071a/fmpy/simulation.py#L18

**Comment by chria** [comment]
This looks indeed like a bug. I'll fix it.
