### ISSUE TITLE
Add `linux-aarch64` support to `conda-forge` release

### ISSUE THREAD

**Issue by mattrobmattrob** [modelon-community/PyFMI#212]
RE: https://anaconda.org/conda-forge/pyfmi/files

This will allow using the Anaconda release on Linux arm64 machines.

https://anaconda.org/conda-forge/numpy/files is an example that already includes support for arm64 Linux machines (`linux-aarch64`).

**Comment by modelonrobinandersson** [comment]
Hi @jschueller, can I assign this to you?

**Comment by sn3kyJ3di** [comment]
Is this still active?  It would be quite valuable to use on constrained hardware.  Thanks!

**Comment by modelonrobinandersson** [comment]
@sn3kyJ3di no update here yet

**Comment by nbungu** [comment]
Why does this has been marked as fixed, when there is still no support for aarch64:

https://anaconda.org/conda-forge/pyfmi/files

Am I missing out on something?

**Comment by modelonrobinandersson** [comment]
@nbungu it has not been marked as fixed, it says "Open" to me.

**Comment by jschueller** [comment]
you can try now

**Comment by modelonrobinandersson** [comment]
Thank you @jschueller, much appreciated!

**Comment by sn3kyJ3di** [comment]
Thank you!
