### ISSUE TITLE
Support for libfortran-9 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by ecosang** [modelon-community/PyFMI#222]
Hi, the pyfmi gets an error to load fmu on Ubuntu>=22.04 because Ubuntu 22.04 does not support libfortran-7 (https://github.com/ylikx/forpy/issues/27). 

Can I request the support of libfortran-9 (i.e., libgfortran.so.5) for Ubuntu 22.04 as many nowadays machine do not support Ubuntu 18.04 or below?
Here is the error message I get on Ubuntu 22.04.

```python
import pyfmi
pyfmi.load_fmu("fmu_test.fmu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyfmi/fmi.pyx", line 8822, in pyfmi.fmi.load_fmu
  File "src/pyfmi/fmi.pyx", line 7062, in pyfmi.fmi.FMUModelCS2.__init__
  File "src/pyfmi/fmi.pyx", line 4169, in pyfmi.fmi.FMUModelBase2.__init__
pyfmi.fmi.InvalidBinaryException: The FMU could not be loaded. Error loading the binary. Could not load the FMU binary: libgfortran.so.4: cannot open shared object file: No such file or directory
```

**Comment by PeterMeisrimelModelon** [comment]
Hi,

this is a problem of the FMU generating tool, since they'd need to package the appropriate libraries resp. versions. 
You'll need to contact the developers of your FMU generating tool.

/Peter

**Comment by ecosang** [comment]
I got it. Thanks. We are using Open source version of old Jmodelica, and that is the reason in my opinion.
Thanks.!
