### ISSUE TITLE
Bug in `get_connection_outputs_discrete` of master.pyx?

### ISSUE THREAD

**Issue by FabiJa** [modelon-community/PyFMI#228]
For a co-simulation of two FMUs I get an error from [here](https://github.com/modelon-community/PyFMI/blob/bb70fc90750d0a4a547f5aa6f00d63ef3e358c86/src/pyfmi/master.pyx#L780):
```
----> [1](vscode-notebook-cell:?execution_count=20&line=1) coupled_simulation.get_connection_outputs_discrete()

File src/pyfmi/master.pyx:773, in pyfmi.master.Master.get_connection_outputs_discrete()

File src/pyfmi/master.pyx:780, in pyfmi.master.Master.get_connection_outputs_discrete()

ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```
I guess the reason is that the `get` function returns a list of arrays for the provided names and line 780 expects one combined numpy array.

Or am I wrong?

**Comment by PeterMeisrimelModelon** [comment]
What are the versions of PyFMI, Python, Numpy & Cython you are using?

**Comment by FabiJa** [comment]
Here you go:
```
cython=3.0.10
python=3.11.8
numpy=1.25.2
```

**Comment by PeterMeisrimelModelon** [comment]
Current PyFMI releases are still on `cython 0.29.x`, so issues with `Cython 3.0.x `are expected. We have an upgrade to `Cython 3 `incoming and are planning a new PyFMI release very soon.

There were a couple of issues similar to what you reported, that should be fixed. You could already try it out now by using the **dev-pm-python311** branch.

**Comment by FabiJa** [comment]
> Current PyFMI releases are still on `cython 0.29.x`, so issues with `Cython 3.0.x `are expected. We have an upgrade to `Cython 3 `incoming and are planning a new PyFMI release very soon.
> 
> There were a couple of issues similar to what you reported, that should be fixed. You could already try it out now by using the **dev-pm-python311** branch.

Thanks. The branch seems so solve this problem.
