### ISSUE TITLE
Jacobian

### ISSUE THREAD

**Issue by Henrik-AI** [modelon-community/PyFMI#23]
Hey, 

according to https://jmodelica.org/pyfmi/pyfmi.html, get_directional_derivative() returns the jacobian mulitplied woth the seed vector v. For using some implicit solvers, the whole jacobian is required. 

Is there any possibility to get access to the n x n jacobian matrix?

In the scope of Reinforcement Learning, this matrix needs to be calculated really often, so an easy access to it would be really helpful. 

Following a code for a manual building of the jacobian, which is quiet ineffective and time-demanding. 

```
model = load_fmu('grid.network.fmu')
Tstart = 0.0 #The start time.
Tend   = 0.02 #The final simulation time.
model.setup_experiment(start_time = Tstart) 
model.enter_initialization_mode()
model.exit_initialization_mode()
model.enter_continuous_time_mode()

states = model.get_states_list()
states_references = [s.value_reference for s in states.values()]
derivatives = model.get_derivatives_list()
derivatives_references = [d.value_reference for d in derivatives.values()]
n_states = len(states)

jacobian = np.zeros([n_states, n_states])
for n in range(0, n_states):
    v = np.zeros(n_states)
    v[n] = 1
    dx = model.get_directional_derivative(states_references, derivatives_references, v)
    jacobian[:,n] = dx
print(jacobian)

```
Any help, suggestions and remarks to my code are really welcome :-)

Thanks in advance!

Henrik

**Comment by chria** [comment]
Hi,

Please have a look at the "get_state_space_representation(A=True, B=False, C=False, D=False)". This will give you the Jacobian directly.

Best
/Christian
