### ISSUE TITLE
 co-simulation

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/PyFMI#231]
How should I perform co-simulation with two FMU files? And how can I obtain FMU files for testing purposes?
Thank you in advance for any suggestion.

**Comment by PeterMeisrimelModelon** [comment]
Hi YanceyYq,

how you _should_ perform co-simulation with two FMUs depends on what you are trying to achieve/simulate.
PyFMI's Master algorithm is one way to connect and simulate multiple CS FMUs jointly.

A simple example is as follows (simplified from [tests/test_fmi_master.py](https://github.com/modelon-community/PyFMI/blob/master/tests/test_fmi_master.py)):

```
from pyfmi import Master
from pyfmi.fmi import FMUModelCS2

model_sub1 = FMUModelCS2("/path/to/LinearCoSimulation_LinearSubSystem1.fmu")
model_sub2 = FMUModelCS2("/path/to/LinearCoSimulation_LinearSubSystem2.fmu")

models = [model_sub1, model_sub2]
connections = [(model_sub1,"y1",model_sub2,"u2"),
            (model_sub2,"y2",model_sub1,"u1")]
master = Master(models, connections)

opts = master.simulate_options()
opts["step_size"] = 0.0005
res = master.simulate(options=opts)
```

using the example FMUs (linux binaries only) located in [https://github.com/modelon-community/PyFMI/tree/master/src/pyfmi/tests/files/FMUs/XML/CS2.0](https://github.com/modelon-community/PyFMI/tree/master/src/pyfmi/tests/files/FMUs/XML/CS2.0).

/Peter

**Comment by YanceyYq** [comment]
Thank you for your response.

**Comment by YanceyYq** [comment]
Are there FMU files available for co-simulation on Windows?

**Comment by YanceyYq** [comment]
When executing this line of code model_sub1 = FMUModelCS2("/path/to/LinearCoSimulation_LinearSubSystem1.fmu"), it throws the following error: pyfmi.fmi.InvalidBinaryException: The FMU could not be loaded. Error loading the binary. The FMU contains no binary for this platform.

**Comment by PeterMeisrimelModelon** [comment]
This is the expected error if you try to load an FMU that only has linux binaries, on Windows.

**Comment by YanceyYq** [comment]
Thank you for your help. I have successfully executed the simulation on Linux. How can I obtain specific data through res?

**Comment by PeterMeisrimelModelon** [comment]
`res` is a dictionary in the form of `{model_index: <ResultObject>}`, the `<Resultobject>` is primarily a `{model_variable: Trajectory} `dictionary.

E.g. `res[0]['x1']` will give you the solution trajectory (as `numpy array`) of `'x1'` from model 0.

Hope this helps to get started.

**Comment by YanceyYq** [comment]
The values of y1_values obtained through y1_values = res[0]['y1'] are being omitted. Why is this happening?
E.g. [-1.47368421e+01 -1.24523839e+01 -1.01518889e+01 ... -8.73190834e-04
 -8.72139590e-04 -8.71095300e-04]

**Comment by PeterMeisrimelModelon** [comment]
Do you mean the `...`? This is standard Python/numpy functionality, that `print(<long list/array>)` will not show all values, and not specific to PyFMI.

/Peter

**Comment by YanceyYq** [comment]
Thank you for your help. My issue has been resolved.
