### ISSUE TITLE
The issue with the model

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/PyFMI#232]
"Could you please tell me what the following warning message means?":
UserWarning: The model, LinearCoSimulation_LinearSubSystem1, does not support directional derivatives which is necessary in-case of an algebraic loop. The simulation might become unstable...
UserWarning: The model, LinearCoSimulation_LinearSubSystem2, does not support directional derivatives which is necessary in-case of an algebraic loop. The simulation might become unstable...

**Comment by YanceyYq** [comment]
Can I assume that these two warnings do not affect the simulation results?

**Comment by PeterMeisrimelModelon** [comment]
Hi YancyYq,

algebraic loops between the model in-&outputs _may_ cause stability issues. If you do not observe any strange results, this warning can be ignored.

The option _linear_correction_ (default: False) can increase robustness in case of stability issues but does require directional derivatives support.

/Peter

**Comment by YanceyYq** [comment]
hi peter
I am performing co-simulation using LinearCoSimulation_LinearSubSystem1.fmu and LinearCoSimulation_LinearSubSystem2.fmu. How do I verify that the data from the co-simulation results are correct?

/YanceyYq

**Comment by PeterMeisrimelModelon** [comment]
In general, this would be up to you to verify. This particular example I gave you in [https://github.com/modelon-community/PyFMI/issues/231#issuecomment-2074411784](https://github.com/modelon-community/PyFMI/issues/231#issuecomment-2074411784) is stable with the default settings.
There is a slight variation of this test that is unstable, see [https://github.com/modelon-community/PyFMI/blob/master/tests/test_fmi_master.py#L345C9-L345C33](https://github.com/modelon-community/PyFMI/blob/master/tests/test_fmi_master.py#L345C9-L345C33)

The results (in absolute value) will go towards infinity.

/Peter

**Comment by YanceyYq** [comment]
hi Peter
It did not tend to infinity. y1 decreased from -14.736842105263158 to -0.0008710952998458588, and y2 decreased from -17.736842105263158 to -0.2601539787262194.
/yancey

**Comment by PeterMeisrimelModelon** [comment]
This sounds correct & stable.

**Comment by YanceyYq** [comment]
Thank you for your answer.
