### ISSUE TITLE
Issue with installation using conda

### ISSUE THREAD

**Issue by michael-MB17** [modelon-community/PyFMI#233]
Hi together,

I am facing this issue when I try to install PyFMI using conda.

![image](https://github.com/modelon-community/PyFMI/assets/138494731/c97071d9-78e0-4357-9d52-73da86cb4c89)

Does it mean that Python 3.12.2 is not supported and the only solution would be to downgrade it to version 3.11?

Thank you in advance

**Comment by modelonrobinandersson** [comment]
Hi @michael-MB17, correct we have not yet added support for 3.12, see https://github.com/modelon-community/PyFMI/issues/203

**Comment by michael-MB17** [comment]
Okay, I see. When the version working with Python 3.12 will be available?

**Comment by modelonrobinandersson** [comment]
> Okay, I see. When the version working with Python 3.12 will be available?

@michael-MB17 unfortunately I don't not in the near future but I propose that you put issue #203 on 'Watch' to get updated as soon as anything happens. We've just added support for `cython 3.x`, well we're not yet done but we are in the process of merging it, and I believe 3.12 will be the next major milestone after that.

**Comment by michael-MB17** [comment]
@modelonrobinandersson Thank you for clarification.

**Comment by jschueller** [comment]
can be closed now
