### ISSUE TITLE
PyFMI 2.13.0 - problem with conda-forge installation

### ISSUE THREAD

**Issue by janpeter19** [modelon-community/PyFMI#238]
Hi,

I install PyFMI 2.13.0 using conda from conda-forge into Ubuntu 22.04 LTS and it does not work.
(I use Python 3.10.12 and Numpy 1.26.4 and Assimulo 3.5.1).

The problem is that when the FMU is loaded I get an error message about Assimulo as follows:

ValueError: assimulo.problem.cProblem size changed, may indicate binary incompatibility. Expected 32 from C header, got 24 from PyObject

It seems also not possible to now use the earlier PyFMI version 2.12.0.

**Comment by PeterMeisrimelModelon** [comment]
@jschueller Do you have an idea what could be the issue here?

From my understanding of the error message (from similar reported issue with numpy), this is likely due to a mismatch of the (Assimulo?) version build used to build PyFMI, vs the one actually installed.

**Comment by janpeter19** [comment]
Good! I can confirm that a few test cases I run on Google Colab
Works just fine using PyFMI 2.13-0 with Assimulo 3.5.1.

Jan Peter

PS Test cases you have here https://github.com/janpeter19

**Comment by janpeter19** [comment]
By the way, is Python 3.10.12 a good environment for PyFMI 2.13-0
or time to step up to Python 3.11 or even 3.12?

FMPy 0.3.20 I run in Python 3.12.3 (at least in Windows).

**Comment by jschueller** [comment]
[3.8-3.11] is ok but 3.12 is not supported yet because of assimulo fortran codes

**Comment by janpeter19** [comment]
Thanks. / Jan Peter

**Comment by PeterMeisrimelModelon** [comment]
@jschueller Thanks for fixing this. 

Am I missing something with the Assimulo fortran codes? The codes should be fine to compile when using std:legacy, or is there some other issues you came across while working on replacing setuptools?

/Peter

**Comment by jschueller** [comment]
same issue:  the fortran codes prevent us from using setuptools and force us to find a replacement for distutils

**Comment by PeterMeisrimelModelon** [comment]
We do intend to keep the Fortran solvers, can you elaborate a bit on the issues with Fortran? (Maybe more suitable in the Assimulo repo in some issue or MR)

**Comment by jschueller** [comment]
see https://github.com/modelon-community/Assimulo/pull/98
we have pyfmi with python 3.12 now (with assimulo fortran solvers disabled though)
I believe this can be closed now

**Comment by janpeter19** [comment]
Good to hear. The earlier fix helped well with Python 3.10.x. Do you suggest to try installation with cones-forge and Python 3.12 and do I need to bother about handling disabled assimulo Fortran solvers? Jan PeterSkickat från min iPhone8 juni 2024 kl. 13:54 skrev Julien Schueller ***@***.***>:﻿
see modelon-community/Assimulo#98
we have pyfmi with python 3.12 now (with assimulo fortran solvers disabled though)
I believe this can be closed now

**Comment by jschueller** [comment]
I think you can pick any version if you dont need the solvers explicitly

**Comment by jschueller** [comment]
yes, this is fine

**Comment by janpeter19** [comment]
Hi,

I made a test using Google Colab which is my usual “demo infrastructure” and upgrading to Python 3.12 did not work at all.
If you like you can try it out yourself.

https://github.com/janpeter19/BPL_TEST2_Perfusion/blob/main/xBPL_TEST2_Perfusion_colab.ipynb <https://github.com/janpeter19/BPL_TEST2_Perfusion/blob/main/xBPL_TEST2_Perfusion_colab.ipynb>

Note, that the second simulation in this notebook gives not the right results after 30 hours, but
This is due to the FMU ME compilation from OpenModelica and the key people there are informed.

For the time being I stay with Python 3.10 and let your competitor FMPy work with Python 3.12.
Would be nice to have them both on Python 3.12, but not a big deal. 
I have at least one example that PyFMI handles better than FMPy. 

Jan Peter

**Comment by modelonrobinandersson** [comment]
Hi @janpeter19 has this issue been resolved?

**Comment by janpeter19** [comment]
Hi

No the issue is not resolved.
However, the link to the notebook was a bit confusing, since when your started it,
a slightly older version with Python 3.10 was loaded and works. 

Now the example in the link is fixed so your really get Python 3.12 and then 
you see that pyfmi that is loaded has severe problems.

Hope you can get it all working with Python 3.12 since “nice” and same as FMPy standard,
but not at all critical for me, and my users. 

Jan Peter

**Comment by modelonrobinandersson** [comment]
Hi @janpeter19, now I understand, thanks for the clarification!

**Comment by jschueller** [comment]
You script is incorrect: your are mixing packages from defaults channel, I suggest to use miniforge instead of miniconda

**Comment by jschueller** [comment]
see https://conda-forge.org/docs/user/tipsandtricks/
