### ISSUE TITLE
Possibility to get solution at specific times

### ISSUE THREAD

**Issue by davidkrantz** [modelon-community/PyFMI#24]
Hello,

I would like to be able to input a list of times where `simulate` should return the solution at, just as it is implemented in Assimulo's function `simulate` with the argument `ncp_list`. Since the FMU solver uses the Assimulo simulation package my guess is that this should be possible. However, I am not able to get it to work.

Am I missing something or is this feature not yet supported?

**Comment by chria** [comment]
Hi,

I'm afraid that this feature is not currently supported through PyFMI.

Best
/Christian
