### ISSUE TITLE
Basic question: Creating FMU's for Model Exchange with pyFMI

### ISSUE THREAD

**Issue by sergiochavezlazo96** [modelon-community/PyFMI#241]
Hello,
I wonder if it is possible to **create** FMU's using PyFMI for Model Exchange. If so, is there any example that I can follow to create the FMU from python source? 
Thank you much in advance.

**Comment by PeterMeisrimelModelon** [comment]
Hi sergiochavezlazo96,

PyFMI is a pure FMI/FMU _import_ tool, what you are looking for is an FMU _export_ tool.

/Peter

**Comment by sergiochavezlazo96** [comment]
Hi @PeterMeisrimelModelon.
Thanks for the answer and clarification. Do you know any exporting tool that use python source to generate FMU's for Model Exchange? I have been looking and I have only found options for Cosimulation (for example pythonFMU). I don't have very clear how people generate their FMU's
Once again, thanks
Sergio

**Comment by PeterMeisrimelModelon** [comment]
I do not have a good overview over the various open available for FMU generation from Python source code, but the [FMI website ](https://fmi-standard.org/tools/) contains a good overview of the various FMI tools and their capabilities. Note that these are self-registered and thus the list may be incomplete. 

A lot of FMU generation is from commercial tools, packaging/exporting their model generated from Modelica, in-house tools or similar.

/Peter
