### ISSUE TITLE
Assert on tolerance failed

### ISSUE THREAD

**Issue by giplessis** [modelon-community/PyFMI#30]
Dear all,
running `fmu_with_input_function.run_demo(with_plots=True)` I get the following error :
```
"Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\gilko\Portables\Miniconda\envs\env_solartrain382\lib\site-packages\pyfmi\examples\fmu_with_input_function.py", line 52, in run_demo
    assert N.abs(res.final('x2')*1.e1 - (-7.30591626709)) < 1e-3
AssertionError"
```

Indeed the value for : `N.abs(res.final('x2')*1.e1 - (-7.30591626709)) = 0.0013945965503356916`

Best regards,

**My configuration**
PyFMI version ................ 2.6 (py38hc8d92b1_0 from conda-forge)
Platform ..................... win32                         
Python version ............... 3.8.2
                
Dependencies: 
Package                        Version                       
-------                        -------                       
assimulo...................... 3.1                           
Cython........................ 0.29.16                       
lxml.......................... 4.5.0                         
matplotlib.................... 3.2.1                         
numpy......................... 1.18.1                        
scipy......................... 1.3.2                         
wxPython...................... --              Package missing - Warning issued, see details below
pyreadline.................... 2.1                           
setuptools.................... 46.1.3.post20200330

**Comment by modelonrobinandersson** [comment]
Hi @giplessis, I noticed this issue never got any attention. I am closing it due to its age, if this is an issue you encounter feel free to open it and we can see if we can get it resolved properly.
