### ISSUE TITLE
After several Model Simulation, Python stopped simulating during load_fmu() call

### ISSUE THREAD

**Issue by MarazziN** [modelon-community/PyFMI#31]
Hi, 
I am loading a FMU model into python and using the PyFMI package to simulate the model (originally developed in OpenModelica).
I am performing a simulations where the FMU model needs to be called several times, and each time a new combinations of model parameters need to be set.
I attach the code:

    %Path to FMU
    curr_dir = O.path.dirname(O.path.abspath(__file__));
    fmu_name = O.path.join(curr_dir,'circuit.fmu')
    %Load to FMU   
    modelFMU = load_fmu(fmu_name, log_file_name='MyLog.txt')
    modelFMU.reset()
    %Set the new parameter and simulation options
    modelFMU.set('A_Tc', Tsim)  
    opts = modelFMU.simulate_options()
    opts["CVode_options"]["store_event_points"] = False                      
    ncp = 10000; 
    opts['ncp'] = ncp;
    %Simulate the model
    res = modelFMU.simulate(final_time= Tsim*9)   

The model runs fine for 1045 runs, and after suddenly stops. 
It does not raise exception, send error message, it just stops the simulation.
I tried to run the model 3 times, and it always stops in the same point (I attach a screenshot), in particular at the load_fmu() call.

I have looked at memory and CPU consumption and it is 40% when the simulation ends.

Do you have any clue for this behavior?
![Problem](https://user-images.githubusercontent.com/64264707/80216738-61a56d80-85f3-11ea-9fc5-b7fd1e4131eb.PNG)

**Comment by modelonrobinandersson** [comment]
@MarazziN I noticed this never got a reply, sorry about that. I am closing this issue due to its age, if this is still an issue feel free to open it up and we can discuss it further.
