### ISSUE TITLE
PyFMI installation issue

### ISSUE THREAD

**Issue by rrahman2020** [modelon-community/PyFMI#42]
Hello:

I am trying to install PyFMI but getting following error (showing some of the error):

fmi.obj : error LNK2001: unresolved external symbol __imp_fmi1_import_get_variable_as_integer
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_create_dllfmu
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_enum_variable_start
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_string_variable_start
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_description
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi1_import_set_real_input_derivatives
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_free_variable_list
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_boolean_variable_start
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_variable_has_start
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_real_variable_nominal
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi1_import_get_capabilities
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_real_type_min
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi1_import_destroy_dllfmu
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi1_import_get_canRejectSteps
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_last_error
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_integer_type_max
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_instantiate
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_real_variable_unit
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_log_forwarding
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_variable_list_size
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_number_of_event_indicators
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_causality
fmi.obj : error LNK2001: unresolved external symbol __imp_fmi2_import_get_variable_declared_type
 
My compiler is Visual Studio 2015. I Compiler FMU library Before that and it compiled without issue.

Will appreciate if you please help on solving this problem.

Thanks

**Comment by tinrabuzin** [comment]
I also have the same issue. Please let me know if you've figured it out.

**Comment by h-bode** [comment]
Have you tried to install it via pip or condaforge?

With pip, there are problems which won´t be fixed

try to run

`conda install -c conda-forge pyfmi`

This should work

**Comment by bressanmarcos** [comment]
As mentioned by @h-bode, it should work perfectly when installing it with `conda install -c conda-forge pyfmi`!
