### ISSUE TITLE
Settings of parameters within models

### ISSUE THREAD

**Issue by h-bode** [modelon-community/PyFMI#48]
Hey there, 

setting the parameters in Python via PyFMI sometimes does not have the demanded result. The value itself ( for example  model.set('resistor.R', 10000) ) gets changed, but the every step in the simulation is done with the default value which was set in OpenModelica itself.

The whole bug is described in 

https://stackoverflow.com/questions/63191419/pyfmi-setting-parameters-sometimes-not-possible-model-depending

I think there are some troubles with PyFMI, so maybe you have any advice for us?

Thanks in advance!

Henrik

**Comment by h-bode** [comment]
Problem solved!

Detailed explanation: 

https://github.com/upb-lea/openmodelica-microgrid-gym/issues/58

**Comment by stheid** [comment]
Basically parameters can only be set, when simulation is in initialization mode

```
model.enter_initialization_mode()
model.set('resistor.R', 1000)
model.set('inductor.L', 1)
model.exit_initialization_mode()
```
