### ISSUE TITLE
Installation Error :PyFMI

### ISSUE THREAD

**Issue by amuntaseer91** [modelon-community/PyFMI#5]
Hello,
I want to use the PyFMI to import my Dymola model in Python. But when I am trying to install, it is showing the following error. i am using pip install PyFMI

(a) `C:\Users\Hiwi09\.PyCharm2018.1\config\scratches>pip install PyFMI
Collecting PyFMI
  Using cached https://files.pythonhosted.org/packages/cc/e5/cf5ecd0a6dcf1b1fff89e7a14de6b3d7888a35b8a2e4db22ddb3a9f9b081/PyFMI-2.4.0.zip
    Complete output from command python setup.py egg_info:
    Der Befehl "gcc" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hiwi09\AppData\Local\Temp\pip-install-2r7paanl\PyFMI\setup.py", line 172, in <module>
        raise Exception("FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.")
Exception: FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Hiwi09\AppData\Local\Temp\pip-install-2r7paanl\PyFMI\

C:\Users\Hiwi09\.PyCharm2018.1\config\scratches>python setup.py install –fmil-home=C:\Users\Hiwi09\FMILibrary-2.0.3-win32\FMILibrary-2.0.3-win32\lib
python: can't open file 'setup.py': [Errno 2] No such file or directory`

How can I solve this? 

Thanks!

**Comment by chria** [comment]
Hi,

Please use the installer available at https://pypi.org/project/PyFMI/#files and let me know if that works.

Best
/Christian

**Comment by Amuntaseer** [comment]
Hello, 
Thank you for the suggestion. The library was installed perfectly, from the given link. But still in the Pycharm it is showing error. I have tried to simulate the sample example of PyFMI (fmi_bouncing_ball_native.py) but still it is showing the following error.

`E:\untitled4\venv\Scripts\python.exe C:/Users/ADNAN/.PyCharmCE2018.1/config/scratches/scratch.py
Traceback (most recent call last):
  File "C:/Users/ADNAN/.PyCharmCE2018.1/config/scratches/scratch.py", line 6, in <module>
    from pyfmi import load_fmu
  File "C:\Python27\lib\site-packages\pyfmi\__init__.py", line 24, in <module>
    from .fmi import FMUModel, load_fmu, FMUModelME1, FMUModelME2
ImportError: DLL load failed: %1 is not a valid Win32 application.

Process finished with exit code 1`

Best Regards

**Comment by chria** [comment]
Ok, one step closer. Are you using Python for 64bits or 32bits?

**Comment by Amuntaseer** [comment]
I am using Python 2.7.15 (64 bit)

**Comment by Tokarzewski** [comment]
I set environ FMIL_HOME and still cant install pyFMI.
Is it possible to set pyFMI for windows 10 64bit with python 3.7+?
I was able to create working environment with conda, but I am trying to work with pure python 3 interpreters.

**Comment by nitingondule** [comment]
I am able to run pyFMI using Conda but installing via pip getting issue. Tried multiple ways but still no luck.
command i used... 
**python setup.py install --fmil-home=D:\Projects\Python\installation\FMILibrary-2.0-win32**

Still it is not working.  any suggestions?  I am using 3.10 python on 64bit windows system.

**Comment by modelonrobinandersson** [comment]
Closing this due to its age, if it is still an issue please make a comment and we can reopen it.

**Comment by Tokarzewski** [comment]
PS C:\Users\BT> pip install PyFMI
Collecting PyFMI
  Using cached PyFMI-2.5.tar.gz (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "C:\Users\BT\AppData\Local\Temp\pip-install-4h7a25gh\pyfmi_43a6d01827c147d7832942130d6b5c80\setup.py", line 38, in <module>
          from Cython.Distutils import build_ext
      ModuleNotFoundError: No module named 'Cython'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\BT\AppData\Local\Temp\pip-install-4h7a25gh\pyfmi_43a6d01827c147d7832942130d6b5c80\setup.py", line 41, in <module>
          raise Exception("Please upgrade to a newer Cython version, >= 0.15.")
      Exception: Please upgrade to a newer Cython version, >= 0.15.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by modelonrobinandersson** [comment]
@Tokarzewski yes the PyFMI available via pip is old and in need of an update. I would suggest you either build it from source or wait until the pypi source has been updated to latest.

**Comment by KMajetta** [comment]
@modelonrobinandersson do you know when the pypi source will be updated? I have he same problem @Tokarzewski mentioned. And the last post to this issue was nearly one year ago

**Comment by modelonrobinandersson** [comment]
> @modelonrobinandersson do you know when the pypi source will be updated? I have he same problem @Tokarzewski mentioned. And the last post to this issue was nearly one year ago

Hi. Unfortunately I don't know when the pypi source will be updated.
However, I have now uploaded two prebuilt wheels for the latest release: https://github.com/modelon-community/PyFMI/releases/tag/PyFMI-2.10.3
Please see the information in the assets-tab regarding the GCC compliance.

If those Python versions are not suitable for your needs I would suggest building PyFMI from source, you can find instructions in `setup.py`.

**Comment by KMajetta** [comment]
> 

Thanks, I will try that
