### ISSUE TITLE
FMILibrary path to PyFMI installer

### ISSUE THREAD

**Issue by Maaeve** [modelon-community/PyFMI#53]
Hi,

I'm trying to install PyFMI, but I can't figure out the real installation problem.
I must admit that I'm quite unexperienced with installing Python packages.
I'm working in Pycharm 2020 1.4 with Python 3.8.5 as a compiler, but due to a problem in pip 20.3, it doesn't allow me to directly implement it there.
As you can see below, I get 2 faults, 1 for pip and 1 for FMI library.
So I tried to to work via pip directly from cmd and then the pip 20.3 problem is fixed, but the FMI library is still occuring.

I downloaded FMI library and unpacked it, but I'm not sure what to do next.
From the readme of FMI library, it tells me to install cmake, but what should I submit as Source and Build directory there?
Should the source directory for CMake be the unpacked FMI library and the Build directory inside my Python scripts or which folders do I need to select?
A Visual studio 2017 compiler for CMake is already installed.
But untill now, the PyFMI installer via CMD still mentions that it can't find --fmil-home.
How and which path should I pass to the installer?

Can someone please advice me.

Collecting PyFMI
  Using cached PyFMI-2.5.tar.gz (4.8 MB)

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\u0135882\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\u0135882\\AppData\\Local\\Temp\\pycharm-packaging\\pyfmi\\setup.py'"'"'; __file__='"'"'C:\\Users\\u0135882\\AppData\\Local\\Temp\\pycharm-packaging\\pyfmi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\u0135882\AppData\Local\Temp\pip-pip-egg-info-719xbb8h'
         cwd: C:\Users\u0135882\AppData\Local\Temp\pycharm-packaging\pyfmi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\u0135882\AppData\Local\Temp\pycharm-packaging\pyfmi\setup.py", line 164, in <module>
        raise Exception("FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.")
    Exception: FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Maaeve** [comment]
Trying with Conda solves the problem,

**Comment by Maaeve** [comment]
Trying with Conda solves the problem.

**Comment by p-klebo** [comment]
> Trying with Conda solves the problem.

Sorry, I have the same issue (only the FMI Issue) trying installation of pyfmi in Anaconda Prompt...
How did you solve it?
Don't know where to save FMILibrary-2.0.3-src or what to do with it...
Help would be great!

**Comment by Maaeve** [comment]
The problems as I stated only occured when I was using Pycharm.
Changing to an Anaconda environment solved the issue as Pycharm was causing conflicts with underlying packages. 
Did you try both install commands in Anaconda (pip and conda)?

**Comment by p-klebo** [comment]
yes I did, 
through conda I get 
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: chria
  channel url: https://conda.binstar.org/chria
  error code: 404

I deleted the channels (default) as in https://github.com/conda/conda/issues/9473  ... still same error

as I understand it, I need to install Assimulo first (tried 'pip install Assimulo') which gives another error which is produced because I think for Assimulo I need at least Sundials (hope I am right, not so used to all this)

seems all like a lot of work to me
thankfully I have a virtual machine with pyfmi but would be great to have it on mine as well...
but maybe not worth the effort
tips would still be great :)

**Comment by p-klebo** [comment]
solved it:

1. opened https://conda.binstar.org/chria in browser and found working command (conda install -c chria pyfmi )
2. opened anaconda prompt as administrator
3. conda install -c chria pyfmi 

That worked!
