### ISSUE TITLE
Glimda import test example

### ISSUE THREAD

**Issue by Maaeve** [modelon-community/PyFMI#54]
Hi,

When I try to run the test example FMI_bouncing_ball, I get the fault 'Could not found GLIMDA'.
The script tries to load GLIMDA from the ...\Assimulo\lib while it is actually in the ...\Assimulo\solvers directory. Is this correct to state?

Thanks in advance.

**Comment by chria** [comment]
Where did you get Assimulo from? GLIMDA requires special build flags to Assimulo for it to work and they seem not to have been provided in the build that you are using. When using Assimulo from PyFMI however, GLIMDA is not a solver that can be chosen for FMUs. So this is not an issue for PyFMI.

**Comment by Maaeve** [comment]
In the mean time, I had a try with Anaconda3 and there no problems are occuring.
I started first in Pycharm via pip, but this causes a lot of problems, while with Anaconda3 the whole PyFMI package is downloaded in a single run.
So the problem is already solved, but anyway thanks for your response.
