### ISSUE TITLE
Can't input objects to multiple FMUs in co-simulations using the Master algorithm

### ISSUE THREAD

**Issue by Denzo77** [modelon-community/PyFMI#58]
I've been trying to load inputs to multiple models while co-simulating and I can't work out how to make it happen.

I have EnergyPlus interacting with 4 FMUs and want to pass some values to each of them (essentially schedules)

When running a cosim, I can pass an input object to master.simulate() like this:
``` python
input_object = [
    (fmu, "input"),
    lambda x: 0,
]
```
However, what I need is the equivalent of something like
``` python
input_object = [
    [
        (fmu_0, "input_0"), (fmu_0, "input_1"), 
        (fmu_1, "input_0"), (fmu_1, "input_1"),
        ....
    ],
    lambda x: [0, 1, 2, 3, ...],
]
```
I couldn't find any documentation on this, so I searched through the code and found this function
https://github.com/modelon-community/PyFMI/blob/fd84831b5c928da8ef76afcf0f566ebee2585488/src/pyfmi/master.pyx#L1328

which seems to be hardcoded to only allow inputs to be set to a single model
``` python
    cpdef set_input(self, double time):
        if self.input_traj is not None:
            u = self.input_traj[1].eval(np.array([time]))[0,:]
            
            for i,m in enumerate(self.input_traj[0]):
                m[0].set(m[1],u[i])   ### here
```

I think I can get the behaviour I want by putting together another fmu to handle it, but that seems like a very cumbersome additional step to pass a list of numbers into the simulation. Is there something I'm overlooking?

**Comment by modelonrobinandersson** [comment]
Hi @Denzo77, I am going through all the open issues at the moment and noticed this thread never got any attention. Is this still an issue for you? I will close this if not, otherwise let me know and we can see if we can get it resolved.
