### ISSUE TITLE
Import pyfmi error

### ISSUE THREAD

**Issue by anandkp92** [modelon-community/PyFMI#59]
I get this error when I tried 
`import pyfmi`

`<path-to-ananconda>/anaconda3/lib/python3.8/site-packages/PyFMI-trunk-py3.8-linux-x86_64.egg/pyfmi/fmi.cpython-38-x86_64-linux-gnu.so: undefined symbol: fmi2_import_get_real_variable_relative_quantity`

It's on a Ubuntu 18.04 machine and I have set up FMILibrary-2.0.3 from https://jmodelica.org/FMILibrary/

Could you help me out here?

**Comment by chria** [comment]
Hi, 
You need a newer version of FMI library, for example this should work: https://github.com/modelon-community/fmi-library/releases/tag/2.2.2

**Comment by anandkp92** [comment]
Hi Christian,

When I run ``make install test``, the installation did not give me any errors, but I received SEFAULTS for the following tests. I believe it could be a dependency issue - but I'm not sure what is the package that I'm missing?

```
64% tests passed, 13 tests failed out of 36

The following tests FAILED:
	  5 - ctest_fmi1_variable_bad_type_variability_test (SEGFAULT)
	  6 - ctest_fmi1_xml_parsing_test (SEGFAULT)
	  7 - ctest_fmi1_type_definitions_test (SEGFAULT)
	  8 - ctest_fmi_import_me_test (SEGFAULT)
	  9 - ctest_fmi_import_cs_test (SEGFAULT)
	 10 - ctest_fmi_import_cs_tc_test (SEGFAULT)
	 11 - ctest_fmi_import_xml_test_empty (SEGFAULT)
	 12 - ctest_fmi_import_xml_test (SEGFAULT)
	 13 - ctest_fmi_import_xml_test_mf (SEGFAULT)
	 16 - ctest_fmi1_logger_test_run (SEGFAULT)
	 17 - ctest_fmi1_logger_test_check (Failed)
	 33 - ctest_fmi_import_test_me_1 (SEGFAULT)
	 34 - ctest_fmi_import_test_cs_1 (SEGFAULT)
Errors while running CTest
```

and most of them had this error: 
```
<path_to_FMILibrary>/fmi-library-2.2.2/Test/fmil_test.h:15:13: note: in expansion of macro ‘TEST_FAILED’
             TEST_FAILED(msg);   
```

Let me know if you want more detailed logs (and where I can find them) to solve this issue! 

Thanks
Anand
