### ISSUE TITLE
Error cannot find the first day when using larger weather file

### ISSUE THREAD

**Issue by AlyElhefny** [modelon-community/PyFMI#63]
I'm facing the following error, when using a custom epw file I have put together using minute by minute weather data: * Fatal * Error occurred on EPW while searching for first day, stopped at 2019/2/16:26 IO Error=-1

The custom weather file runs well on energyplus but this problem occurs when simulating fmus through pyfmi.

The setup works only if the start time is anywhere between January and somewhere in February. Any other start day beyond that will crash by this error. 

It looks like the code gives up relatively early on finding the start day. This problem does not happen when running hourly TMY file but rather with the larger minute resolution weather file.

**Comment by chria** [comment]
I don't believe this is something for PyFMI.
