### ISSUE TITLE
pyfmi.fmi.FMUException: Failed to get the Integer values in FMU without integer output variables

### ISSUE THREAD

**Issue by Mierpo** [modelon-community/PyFMI#64]
Hi,

I'm using PyFMI 2.4 to do some performance testing on an FMU model. This model does not contain any integer output variables, but for some reason I run into an internal pyfmi error when simulating the model. Code:
```

from pyfmi import load_fmu
model = load_fmu("model.fmu")
model.setup_experiment()
model.enter_initialization_mode()
model.exit_initialization_mode()
opts = model.simulate_options()
opts["ncp"] = 10
res = model.simulate(final_time=1.0, options=opts)
```

Trace:

```
Traceback (most recent call last):
  File "C:/Users/USERNAME/PycharmProjects/pyfmi/main.py", line 8,
    res = model.simulate(final_time=1.0, options=opts)
  File "src\pyfmi\fmi.pyx", line 6160, in pyfmi.fmi.FMUModelCS2.simulate (src\pyfmi\fmi.c:71500)
  File "src\pyfmi\fmi.pyx", line 311, in pyfmi.fmi.ModelBase._exec_simulate_algorithm (src\pyfmi\fmi.c:6517)
  File "src\pyfmi\fmi.pyx", line 305, in pyfmi.fmi.ModelBase._exec_simulate_algorithm (src\pyfmi\fmi.c:6406)
  File "C:\Users\USERNAME\Miniconda3\envs\pyfmi_35_venv\lib\site-packages\pyfmi\fmi_algorithm_drivers.py", line 981, in __init__
    self.result_handler.simulation_start()
  File "C:\Users\USERNAME\Miniconda3\envs\pyfmi_35_venv\lib\site-packages\pyfmi\common\io.py", line 1850, in simulation_start
    " %.14E" % (self.model.get_integer([vref])))
  File "src\pyfmi\fmi.pyx", line 3542, in pyfmi.fmi.FMUModelBase2.get_integer (src\pyfmi\fmi.c:41802)
pyfmi.fmi.FMUException: Failed to get the Integer values.

```

Unfortunately I cannot provide the FMU for testing here due to confidentiality. However, I can provide a redacted modelDescription.xml:

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<fmiModelDescription
  fmiVersion="2.0"
  modelName="Model"
  guid="{foobar}"
  numberOfEventIndicators="0">
	
  <CoSimulation
    modelIdentifier="Model"
    canHandleVariableCommunicationStepSize="true"
    canBeInstantiatedOnlyOncePerProcess="true"
    canGetAndSetFMUstate="false"
    canInterpolateInputs="false"
    providesDirectionalDerivative="false"
    canRunAsynchronuously="false">
  </CoSimulation>

  <LogCategories>
    <Category name="logAll"/>
    <Category name="logStatusError"/>
    <Category name="logStatusWarning"/>
    <Category name="logStatusFatal"/>
    <Category name="logStatusPending"/>
    <Category name="logStatusDiscard"/>
  </LogCategories>

  <ModelVariables>
    
	<!-- bunch of Real and Boolean type inputs and outputs -->
	
	<ScalarVariable name="IntegerParameter" valueReference="0" description=""
                    causality="parameter" variability="fixed" initial="exact">
      <Integer start="1"/>
    </ScalarVariable>

	</ModelVariables>
	<ModelStructure>

    <Outputs>
		<!-- redacted -->
    </Outputs>
	</ModelStructure>
</fmiModelDescription>

```

From my understanding, pyfmi seems to be doing something like this when the problem occurs:

```
        # write constants and parameters
        for i, dtype in enumerate(list_of_parameters):
            vref = dtype[0]
            if dtype[1] == fmi.FMI_REAL:
                str_text = str_text + (
                    " %.14E" % (self.model.get_real([vref])))
            elif dtype[1] == fmi.FMI_INTEGER or dtype[1] == fmi.FMI_ENUMERATION:
                str_text = str_text + (
                    " %.14E" % (self.model.get_integer([vref])))
            elif dtype[1] == fmi.FMI_BOOLEAN:
                str_text = str_text + (
                    " %.14E" % (float(
                        self.model.get_boolean([vref])[0])))

```

Which means it's reading the parameter value from the FMU model, instead of the modelDescription.xml, which causes the issue. Note: Setting the parameter value before calling simulate, e.g. with model.set("IntegerParameter", 1), also causes the exception to be thrown.

Further information:

1. Running the model with fmi 2 compliance checker works without issues.
2. Adding a new integer output variable in the modelDescription.xml (with a value reference that is not mapped in the implementing .dll / .so model), makes fmu compliance checker correctly sees a warning and value of 0 being written to the output result of the new integer output variable. Pyfmi should also see a warning and get a 0 when attempting to get integer value references that do not exist in the FMU - this is how the model has been built.

Any ideas how to configure pyfmi to not throw an exception and/or stop it from attempting to read variables that aren't outputs?

**Comment by chria** [comment]
Have you checked the log to see if the FMU outputs any warning?

Also note that, in your script you manually initialize the FMU (through the calls to enter/exit initialization). This means that you need to make sure that you do not initialize again in the call to the simulate method. I.e. you need to send in the option "initialize" False. The other option is that you simply do:

`
from pyfmi import load_fmu

model = load_fmu("model.fmu")

opts = model.simulate_options()

opts["ncp"] = 10

res = model.simulate(final_time=1.0, options=opts)
`

By default, PyFMI will store all variables that are exposed in the FMUs modelDescription. If all of those variables cannot be retrieved from the FMU, it is not a correct FMU. You can change this behaviour by using the "filter" functionality:

`
opts["filter"] = "summary*" #Only store variables that start with summary in the name
`

**Comment by Mierpo** [comment]
Am I correct to assume that the exception that I encountered is thrown if the FMU sends a warning on getValue? From FMU 2 specs:

```
fmi2Warning – things are not quite right, but the computation can continue. Function “logger” was
called in the model (see below) and it is expected that this function has shown the prepared
information message to the user.
```

Essentially, the FMU works as follows:

1. User must set a parameter "communication point" ("IntegerParameter" in my above example)
2.1 If user sets the communication point, they can get values (fmi2Ok status on getters)
2.2 If user does not set communication point, FMU will return ( fmi2Warning on getters)

I do not run into the exception in this scenario:

```
from pyfmi import load_fmu
model = load_fmu("model.fmu")
model.setup_experiment()
model.enter_initialization_mode()
model.set("IntegerParameter", 1)
model.exit_initialization_mode()
opts = model.simulate_options()
opts["ncp"] = 10
opts["initialize"] = False
opts["filter"] = "PreciseNameOfExactlyOneRealOutputVariableHere"
res = model.simulate(final_time=1.0, options=opts)
```

However, I run into the exception in this scenario:

```
from pyfmi import load_fmu
model = load_fmu("model.fmu")
model.setup_experiment()
model.enter_initialization_mode()
# Removed parameter setter line
model.exit_initialization_mode()
opts = model.simulate_options()
opts["ncp"] = 10
opts["initialize"] = False
opts["filter"] = "PreciseNameOfExactlyOneRealOutputVariableHere"
res = model.simulate(final_time=1.0, options=opts)
```

This leads me to believe that pyfmi (incorrectly) throws an exception when an fmi2Warning status is received from the getters. Correct me if I'm wrong.

**Comment by dhblum** [comment]
I'm sorry, I did not mean to mention this issue, instead I meant https://github.com/modelon-community/PyFMI/issues/72.  I do not know how to remove a mention.

**Comment by modelonrobinandersson** [comment]
Hi @Mierpo, is this issue still active in the latest version of PyFMI? If so, please reply and I will reopen this.
