### ISSUE TITLE
Co-simulate two co-simulation type of FMUs

### ISSUE THREAD

**Issue by manasdas17** [modelon-community/PyFMI#83]
Hello,
How to co-simulate two co-simulation type of FMUs connected in a feedback loop
by using PyFMI ? The simulation setup looks like in the figure attached.

Regards,
![2_fmu_simulation](https://user-images.githubusercontent.com/1115602/115244083-36d7f180-a141-11eb-963a-137616e33a53.png)

**Comment by chria** [comment]
Hi, use the available master algorithm. For examples see https://portal.research.lu.se/portal/files/7201641/pyfmi_tech.pdf
