### ISSUE TITLE
Set Input Issue in Coupled FMU simulation

### ISSUE THREAD

**Issue by manasdas17** [modelon-community/PyFMI#87]
Hello, I'm trying to simulate coupled FMUs of co-simulation type.
However, while trying to set input values, i'm getting some error.
Please guide.

```
import pyfmi
from pyfmi import load_fmu
from pyfmi.master import Master
import pylab as P
import numpy as np

sub_system1 = load_fmu("Simple_System_PI.fmu")
sub_system2 = load_fmu("Simple_System_Plant.fmu")
models = [sub_system1, sub_system2]

connections = [( sub_system1 ,"y",sub_system2 ,"u"),
                ( sub_system2 ,"y",sub_system1 ,"u")]

# input = ('u[0]', 4.0)
# Generate input
t = np.linspace (0, 10, 100)
u = np.cos(t)
u_traj = np.transpose(np.vstack((t,u)))
input_object = ('u', u_traj)
#print(input_object)
sub_system1.set('u',u[0])


master_simulator = Master (models, connections)
res = master_simulator.simulate(start_time = 0.0, final_time = 10.0, input = input_object)
```

Here is the error 
`Traceback (most recent call last):
  File "Simple_PI_SImple_Plant.py", line 25, in <module>
    res = master_simulator.simulate(start_time = 0.0, final_time = 10.0, input = input_object)
  File "src\pyfmi\master.pyx", line 1434, in pyfmi.master.Master.simulate
  File "src\pyfmi\master.pyx", line 1037, in pyfmi.master.Master.initialize
  File "src\pyfmi\master.pyx", line 1333, in pyfmi.master.Master.set_input
AttributeError: 'str' object has no attribute 'set'`

PFA for the FMUs.
[Test.zip](https://github.com/modelon-community/PyFMI/files/6375634/Test.zip)

**Comment by agnesramle** [comment]
You need to specify the fmu as well for the input object, i.e. input_object = ((sub_system1, 'u'), u_traj).

**Comment by manasdas17** [comment]
This works. But the issue right now is 
1. all the results are coming to zero in the coupled FMU simulation set-up.
2. For which, I guess the issue is, I'm trying to provide the input to "u" in sub_system1 but which should be given to "y_ref" (PFA
![simulation_setup](https://user-images.githubusercontent.com/1115602/116869408-4faad180-ac2e-11eb-92da-bf77cc582f02.png)
 for the image). But the "sum block" is not part of the sub_system1 FMU. Is it the correct approach? If yes, please guide how the connections and set up to be defined for this coupled FMU simulation.

**Comment by chria** [comment]
I'm afraid that the current master algorithm only supports direct connections. It does not support addition/subtraction between signals. This needs to be a separate FMU or this logic needs to be inside one of the other FMUs.
